language: ruby
dist: trusty
rvm:
- 2.5.3
before_install:
- gem install bundler -v '2.0.2'
before_script:
- gem update --system '3.0.6'
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script: 
services:
- postgresql
notifications:
  email: false
env:
  global:
  - secure: Tgnmiaw8/wcXMA7F2G4ZiQg48rNufGWsaypb4qbVDob1hX0yGIhdkLxN62sPQG4WwhRaRPE/9R4/p4JCAauAj2WDTdTD6QMOVWcHrvI/QdfKevwKP+JCa6l6qzpT0UKnkaSD00d5C5A+1EmwUajrMA26vaTDo0Bv1Gnk5nvaJ6YWvw6s8C9wADtA4OLh6tHNGmgUFNiswFHzcc8803QQEoNMcMCJ6dwe1E1SHbN2CeIYm4mibXBqOBNtxKxYK4NxnnEL3oNMVbpoxWR3LSkcd+qwS9bRsiQl5oMw6z1mcBXJ/uYoFkEAFQegPCN+1QIwU+K4OPyaCl9L7q5qgzG16eZcaUPKlAyYZX62KWG0W2pMr6glTb9wm8NAZJOFdPNBVq0vsikLSH5K+KeLRZS7ZDwYu4kQTRHKCH7zZ88zqTLeqz+9nkRlzWs4wsKPsz4zGb1ObDFeTWzyfBmQe92Wz2RLAyWEfwpnaKah5aTJ8dKay30Mt1lJBRSCPNV1QZMV5oCoQ5gYIYEMJzVDOK4/jrIj5KkwkreDYLBBcUxSSOk/QiIoFQo5mHN7cLoNWWv3d+HBY2eBSQIN1lQrwqUHNrleYsnBbkQCXm+kUo6s/jvdGLDMGlnV3mWQSWu4kXtsIuYrAZiclezu5hpTbLooSpprhMHftzttc1TewnQ6vnI=
  - secure: badwc1PTKp8p/f2fqr/bTrexUEAWevRdxllkxyUHOz8BEduQ0+NTAPXyUk8xKCmrmNJd7N6LGmjsyfbB07JTHDyRQylE/zx8r3AJu5tJxavSzwKrkZ/nmD2PeGQmU8QAKdkks5BqZ+ZtkfHXKJXRYlaa4dh9YIdIjjgxOIGOrCI9agArZqk5AyjabSDQTg6MKOpj5jTaqj36mEIzaPH+c/XRwvDUTogcEmQnE1LEz4AubNN3bD5hoMNCQojWHxokxGZJlCSwLZDq0vGZKuXMRvc4eJb453Ol/uWXbqyi7hly/yZLSiqnHZhSGMb6zKaIX2Pyh/JDvD2d4x0bTeTGEEaLRkoq0X8QfKGls5iEgDZ4C8m4444+Ou8AxAaKfRmRwZ2X3PkUhNTIDTdbarGdC2fFBqlSzx0EEi4/80ifb6qo1iI1IsuQ/x3Z8OcszTD/B3JoOPU/rUlq+Ma8tK8tAQcEHUDq6QQEPZ6ZzhN8WIaQIuMbaFjkA+WcVBKbm0AIq7w0Pmse5L5Ea06fLJc8yJdpANCovCBjRgms+Iw7cw5JwWPRIqhhiQsYctbTXEFRUmN+8TN7gzWx3WCEbyy8bBzvYX25ITLXITHL6GqZsRNZvCnPaCNRLDCF44sEVs1EDsJXo/uALlFh6v/aTH5s+3dkQMRWqL1YuKrNzIevN+g=
